/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DailyVaultRouteImport } from './routes/daily-vault'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UpdatesIndexRouteImport } from './routes/updates.index'
import { Route as UnitsIndexRouteImport } from './routes/units.index'
import { Route as SummonsIndexRouteImport } from './routes/summons.index'
import { Route as LoadoutsIndexRouteImport } from './routes/loadouts.index'
import { Route as EditorsIndexRouteImport } from './routes/editors.index'
import { Route as ChestsIndexRouteImport } from './routes/chests.index'
import { Route as UpdatesSlugRouteImport } from './routes/updates.$slug'
import { Route as UnitsSlugRouteImport } from './routes/units.$slug'
import { Route as SummonsSlugRouteImport } from './routes/summons.$slug'
import { Route as ChestsSlugRouteImport } from './routes/chests.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as LoadoutsCommunityIndexRouteImport } from './routes/loadouts.community.index'
import { Route as LoadoutsCommunityIdRouteImport } from './routes/loadouts.community.$id'

const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyVaultRoute = DailyVaultRouteImport.update({
  id: '/daily-vault',
  path: '/daily-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesIndexRoute = UpdatesIndexRouteImport.update({
  id: '/updates/',
  path: '/updates/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsIndexRoute = UnitsIndexRouteImport.update({
  id: '/units/',
  path: '/units/',
  getParentRoute: () => rootRouteImport,
} as any)
const SummonsIndexRoute = SummonsIndexRouteImport.update({
  id: '/summons/',
  path: '/summons/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadoutsIndexRoute = LoadoutsIndexRouteImport.update({
  id: '/loadouts/',
  path: '/loadouts/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorsIndexRoute = EditorsIndexRouteImport.update({
  id: '/editors/',
  path: '/editors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChestsIndexRoute = ChestsIndexRouteImport.update({
  id: '/chests/',
  path: '/chests/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesSlugRoute = UpdatesSlugRouteImport.update({
  id: '/updates/$slug',
  path: '/updates/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsSlugRoute = UnitsSlugRouteImport.update({
  id: '/units/$slug',
  path: '/units/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SummonsSlugRoute = SummonsSlugRouteImport.update({
  id: '/summons/$slug',
  path: '/summons/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChestsSlugRoute = ChestsSlugRouteImport.update({
  id: '/chests/$slug',
  path: '/chests/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LoadoutsCommunityIndexRoute = LoadoutsCommunityIndexRouteImport.update({
  id: '/loadouts/community/',
  path: '/loadouts/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadoutsCommunityIdRoute = LoadoutsCommunityIdRouteImport.update({
  id: '/loadouts/community/$id',
  path: '/loadouts/community/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/daily-vault': typeof DailyVaultRoute
  '/feedback': typeof FeedbackRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chests/$slug': typeof ChestsSlugRoute
  '/summons/$slug': typeof SummonsSlugRoute
  '/units/$slug': typeof UnitsSlugRoute
  '/updates/$slug': typeof UpdatesSlugRoute
  '/chests/': typeof ChestsIndexRoute
  '/editors/': typeof EditorsIndexRoute
  '/loadouts/': typeof LoadoutsIndexRoute
  '/summons/': typeof SummonsIndexRoute
  '/units/': typeof UnitsIndexRoute
  '/updates/': typeof UpdatesIndexRoute
  '/loadouts/community/$id': typeof LoadoutsCommunityIdRoute
  '/loadouts/community/': typeof LoadoutsCommunityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/daily-vault': typeof DailyVaultRoute
  '/feedback': typeof FeedbackRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chests/$slug': typeof ChestsSlugRoute
  '/summons/$slug': typeof SummonsSlugRoute
  '/units/$slug': typeof UnitsSlugRoute
  '/updates/$slug': typeof UpdatesSlugRoute
  '/chests': typeof ChestsIndexRoute
  '/editors': typeof EditorsIndexRoute
  '/loadouts': typeof LoadoutsIndexRoute
  '/summons': typeof SummonsIndexRoute
  '/units': typeof UnitsIndexRoute
  '/updates': typeof UpdatesIndexRoute
  '/loadouts/community/$id': typeof LoadoutsCommunityIdRoute
  '/loadouts/community': typeof LoadoutsCommunityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/daily-vault': typeof DailyVaultRoute
  '/feedback': typeof FeedbackRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/chests/$slug': typeof ChestsSlugRoute
  '/summons/$slug': typeof SummonsSlugRoute
  '/units/$slug': typeof UnitsSlugRoute
  '/updates/$slug': typeof UpdatesSlugRoute
  '/chests/': typeof ChestsIndexRoute
  '/editors/': typeof EditorsIndexRoute
  '/loadouts/': typeof LoadoutsIndexRoute
  '/summons/': typeof SummonsIndexRoute
  '/units/': typeof UnitsIndexRoute
  '/updates/': typeof UpdatesIndexRoute
  '/loadouts/community/$id': typeof LoadoutsCommunityIdRoute
  '/loadouts/community/': typeof LoadoutsCommunityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/daily-vault'
    | '/feedback'
    | '/admin'
    | '/chests/$slug'
    | '/summons/$slug'
    | '/units/$slug'
    | '/updates/$slug'
    | '/chests/'
    | '/editors/'
    | '/loadouts/'
    | '/summons/'
    | '/units/'
    | '/updates/'
    | '/loadouts/community/$id'
    | '/loadouts/community/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/daily-vault'
    | '/feedback'
    | '/admin'
    | '/chests/$slug'
    | '/summons/$slug'
    | '/units/$slug'
    | '/updates/$slug'
    | '/chests'
    | '/editors'
    | '/loadouts'
    | '/summons'
    | '/units'
    | '/updates'
    | '/loadouts/community/$id'
    | '/loadouts/community'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/daily-vault'
    | '/feedback'
    | '/_authenticated/admin'
    | '/chests/$slug'
    | '/summons/$slug'
    | '/units/$slug'
    | '/updates/$slug'
    | '/chests/'
    | '/editors/'
    | '/loadouts/'
    | '/summons/'
    | '/units/'
    | '/updates/'
    | '/loadouts/community/$id'
    | '/loadouts/community/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DailyVaultRoute: typeof DailyVaultRoute
  FeedbackRoute: typeof FeedbackRoute
  ChestsSlugRoute: typeof ChestsSlugRoute
  SummonsSlugRoute: typeof SummonsSlugRoute
  UnitsSlugRoute: typeof UnitsSlugRoute
  UpdatesSlugRoute: typeof UpdatesSlugRoute
  ChestsIndexRoute: typeof ChestsIndexRoute
  EditorsIndexRoute: typeof EditorsIndexRoute
  LoadoutsIndexRoute: typeof LoadoutsIndexRoute
  SummonsIndexRoute: typeof SummonsIndexRoute
  UnitsIndexRoute: typeof UnitsIndexRoute
  UpdatesIndexRoute: typeof UpdatesIndexRoute
  LoadoutsCommunityIdRoute: typeof LoadoutsCommunityIdRoute
  LoadoutsCommunityIndexRoute: typeof LoadoutsCommunityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-vault': {
      id: '/daily-vault'
      path: '/daily-vault'
      fullPath: '/daily-vault'
      preLoaderRoute: typeof DailyVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/': {
      id: '/updates/'
      path: '/updates'
      fullPath: '/updates/'
      preLoaderRoute: typeof UpdatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units/': {
      id: '/units/'
      path: '/units'
      fullPath: '/units/'
      preLoaderRoute: typeof UnitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summons/': {
      id: '/summons/'
      path: '/summons'
      fullPath: '/summons/'
      preLoaderRoute: typeof SummonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loadouts/': {
      id: '/loadouts/'
      path: '/loadouts'
      fullPath: '/loadouts/'
      preLoaderRoute: typeof LoadoutsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editors/': {
      id: '/editors/'
      path: '/editors'
      fullPath: '/editors/'
      preLoaderRoute: typeof EditorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chests/': {
      id: '/chests/'
      path: '/chests'
      fullPath: '/chests/'
      preLoaderRoute: typeof ChestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/$slug': {
      id: '/updates/$slug'
      path: '/updates/$slug'
      fullPath: '/updates/$slug'
      preLoaderRoute: typeof UpdatesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units/$slug': {
      id: '/units/$slug'
      path: '/units/$slug'
      fullPath: '/units/$slug'
      preLoaderRoute: typeof UnitsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summons/$slug': {
      id: '/summons/$slug'
      path: '/summons/$slug'
      fullPath: '/summons/$slug'
      preLoaderRoute: typeof SummonsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chests/$slug': {
      id: '/chests/$slug'
      path: '/chests/$slug'
      fullPath: '/chests/$slug'
      preLoaderRoute: typeof ChestsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/loadouts/community/': {
      id: '/loadouts/community/'
      path: '/loadouts/community'
      fullPath: '/loadouts/community/'
      preLoaderRoute: typeof LoadoutsCommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loadouts/community/$id': {
      id: '/loadouts/community/$id'
      path: '/loadouts/community/$id'
      fullPath: '/loadouts/community/$id'
      preLoaderRoute: typeof LoadoutsCommunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DailyVaultRoute: DailyVaultRoute,
  FeedbackRoute: FeedbackRoute,
  ChestsSlugRoute: ChestsSlugRoute,
  SummonsSlugRoute: SummonsSlugRoute,
  UnitsSlugRoute: UnitsSlugRoute,
  UpdatesSlugRoute: UpdatesSlugRoute,
  ChestsIndexRoute: ChestsIndexRoute,
  EditorsIndexRoute: EditorsIndexRoute,
  LoadoutsIndexRoute: LoadoutsIndexRoute,
  SummonsIndexRoute: SummonsIndexRoute,
  UnitsIndexRoute: UnitsIndexRoute,
  UpdatesIndexRoute: UpdatesIndexRoute,
  LoadoutsCommunityIdRoute: LoadoutsCommunityIdRoute,
  LoadoutsCommunityIndexRoute: LoadoutsCommunityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
